name: currency
description: pet project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_bloc: ^7.3.1
  provider: ^6.0.1
  shared_preferences: ^2.0.7
  http: ^0.13.3
  equatable: ^2.0.3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  retrofit: ^3.0.0
  dio: ^4.0.4
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  json_serializable: ^6.1.1
  retrofit_generator: ^3.0.0+2

flutter:

  uses-material-design: true
